#!/usr/bin/env ruby

require 'triglav/agent/bigquery'
Triglav::Agent::Configuration.configure do |config|
  config.name = :bigquery
  # config.cli_class = Triglav::Agent::Bigquery::CLI
  # config.setting_class = Triglav::Agent::Bigquery::Setting
  # config.worker_module = Triglav::Agent::Bigquery::Worker
  # config.processor_class = Triglav::Agent::Bigquery::Processor
  config.monitor_class = Triglav::Agent::Bigquery::Monitor
  config.connection_class = Triglav::Agent::Bigquery::Connection
end
Triglav::Agent::Configuration.cli_class.new.run
